### ISSUE TITLE
Barcode to scan items

### ISSUE THREAD

**Issue by esteban24munoz** [TheTableHU/tablecloth#32]
Create a QR code column to scan items more efficiently

**Comment by esteban24munoz** [comment]
Get a Bar code scanner from Amazon

**Comment by hengelcen** [comment]
I found this API to get product data from the barcode (UPC). This will be useful when adding new items to the inventory.
https://www.upcitemdb.com/

**Comment by hengelcen** [comment]
https://www.upcindex.com/

**Comment by esteban24munoz** [comment]
The Table's team approved the idea

**Comment by hengelcen** [comment]
Functionality has been added, tested and is currently in production.
Improvements:
Add item: Users only need to scan an item and the system will retrieve product data such as name and image from the internet.
Shipment and Check out: It is only needed to scan the items, changed the GUI.
